# Generated by Django 6.1.1 on 2026-09-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Soroush Eghdami', max_length=120)),
                ('username', models.CharField(default='soroush', max_length=60)),
                ('role', models.CharField(default='Python Backend Developer', max_length=120)),
                ('tagline', models.CharField(default='Django · REST APIs · Docker · AI-powered RAG systems', max_length=255)),
                ('location', models.CharField(default='404: Location Not Found', max_length=120)),
                ('education', models.CharField(default='Computer Engineering (Operating Systems, Computer Vision)', max_length=255)),
                ('bio', models.JSONField(default=list)),
                ('fun_fact', models.CharField(default='needs_coffee() -> always True', max_length=255)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('github_url', models.URLField(default='https://github.com/Soroush-Eghdami')),
                ('followers', models.IntegerField(default=0)),
                ('public_repos', models.IntegerField(default=0)),
                ('resume_url', models.CharField(blank=True, default='', max_length=255)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('desc', models.TextField(blank=True, default='')),
                ('stack', models.JSONField(default=list)),
                ('link', models.URLField()),
                ('stars', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-featured', '-stars', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120, unique=True)),
                ('items', models.JSONField(default=list)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'category'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'label'],
            },
        ),
    ]
